/**
 * Generated by scripts/vega-enums.mjs from the installed vega's schema.
 * Do not edit.
 */
export const VEGA_ENUMS = {
  blend: [
    'multiply',
    'screen',
    'overlay',
    'darken',
    'lighten',
    'color-dodge',
    'color-burn',
    'hard-light',
    'soft-light',
    'difference',
    'exclusion',
    'hue',
    'saturation',
    'color',
    'luminosity',
  ],
  strokeCap: ['butt', 'round', 'square'],
  strokeJoin: ['miter', 'round', 'bevel'],
  align: ['left', 'right', 'center'],
  baseline: ['top', 'middle', 'bottom', 'alphabetic'],
};
