/**
 * Regenerates releases/vega-enums.js, the value lists the mark playground fills
 * its pickers from. They come out of the installed vega's own schema rather
 * than a copy kept here, so a vega release that adds a stroke cap or a blend
 * mode shows up on the page as soon as the dependency moves.
 */
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const out = join(root, 'releases', 'vega-enums.js');
const require = createRequire(import.meta.url);

/** The enum a `<prop>Value` definition allows as a literal value. */
function valueEnum(schema, name) {
  const def = schema.definitions?.[name];
  if (!def) {
    throw new Error(`vega's schema has no ${name}`);
  }
  const found = [];
  const walk = node => {
    if (Array.isArray(node)) {
      node.forEach(walk);
      return;
    }
    if (!node || typeof node !== 'object') {
      return;
    }
    if (Array.isArray(node.enum) && node.enum.length > found.length) {
      found.length = 0;
      found.push(...node.enum);
    }
    Object.values(node).forEach(walk);
  };
  walk(def);
  if (found.length === 0) {
    throw new Error(`no enum under ${name}`);
  }
  // null stands for the default, which each picker names itself
  return found.filter(v => typeof v === 'string');
}

/** vega's package root, which its exports map does not hand out directly. */
function vegaRoot() {
  let dir = dirname(require.resolve('vega'));
  for (let up = 0; up < 6; up++) {
    try {
      const pkg = JSON.parse(readFileSync(join(dir, 'package.json'), 'utf8'));
      if (pkg.name === 'vega') {
        return dir;
      }
    } catch {
      // keep walking
    }
    dir = dirname(dir);
  }
  throw new Error('vega is not installed');
}

const schema = JSON.parse(readFileSync(join(vegaRoot(), 'build', 'vega-schema.json'), 'utf8'));
const enums = {
  blend: valueEnum(schema, 'blendValue'),
  strokeCap: valueEnum(schema, 'strokeCapValue'),
  strokeJoin: valueEnum(schema, 'strokeJoinValue'),
};

const body =
  `/**\n` +
  ` * Generated by scripts/vega-enums.mjs from the installed vega's schema.\n` +
  ` * Do not edit.\n` +
  ` */\n` +
  `export const VEGA_ENUMS = ${JSON.stringify(enums, null, 2)};\n`;

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  let before = '';
  try {
    before = readFileSync(out, 'utf8');
  } catch {
    before = '';
  }
  writeFileSync(out, body);
  // The comparison is against the formatted file, not the string written here:
  // prettier reshapes the JSON and keeps the working tree on crlf, so a raw
  // comparison would report a rewrite on every run. npx is a .cmd shim on
  // Windows, so it needs a shell.
  execFileSync('npx', ['prettier', '--write', '--log-level', 'warn', 'releases/vega-enums.js'], {
    cwd: root,
    stdio: 'inherit',
    shell: process.platform === 'win32',
  });
  const counts = Object.entries(enums)
    .map(([k, v]) => `${k} ${v.length}`)
    .join(', ');
  console.log(
    readFileSync(out, 'utf8') === before
      ? `releases/vega-enums.js is already current: ${counts}`
      : `releases/vega-enums.js rewritten: ${counts}`,
  );
}

export { enums };
